import { motion } from 'framer-motion';
import { ChartCard } from '@/components/ChartCard';
import { GlassPanel } from '@/components/GlassPanel';
import { personalityData } from '@/data/mockData';
import { Brain, Sparkles } from 'lucide-react';
import { RadarChart, PolarGrid, PolarAngleAxis, Radar, ResponsiveContainer } from 'recharts';
import { cn } from '@/lib/utils';

const bigFiveData = [
  { trait: 'Openness', value: personalityData.bigFive.openness, fullMark: 100 },
  { trait: 'Conscientiousness', value: personalityData.bigFive.conscientiousness, fullMark: 100 },
  { trait: 'Extraversion', value: personalityData.bigFive.extraversion, fullMark: 100 },
  { trait: 'Agreeableness', value: personalityData.bigFive.agreeableness, fullMark: 100 },
  { trait: 'Neuroticism', value: personalityData.bigFive.neuroticism, fullMark: 100 },
];

const colorClasses = {
  cyan: 'from-neon-cyan/30 to-neon-cyan/5 border-neon-cyan/40 text-neon-cyan',
  purple: 'from-neon-purple/30 to-neon-purple/5 border-neon-purple/40 text-neon-purple',
  pink: 'from-neon-pink/30 to-neon-pink/5 border-neon-pink/40 text-neon-pink',
  blue: 'from-neon-blue/30 to-neon-blue/5 border-neon-blue/40 text-neon-blue',
};

const Personality = () => {
  return (
    <div className="space-y-6 max-w-7xl mx-auto">
      {/* Header */}
      <motion.div
        initial={{ opacity: 0, y: -20 }}
        animate={{ opacity: 1, y: 0 }}
      >
        <h1 className="font-display text-3xl font-bold">
          Your <span className="gradient-text">Personality</span> Profile
        </h1>
        <p className="text-muted-foreground mt-1">
          Deep insights into who you are, based on your digital behavior.
        </p>
      </motion.div>

      <div className="grid lg:grid-cols-2 gap-6">
        {/* Big Five Radar Chart */}
        <ChartCard
          title="Big Five Personality Traits"
          subtitle="Your psychological profile based on the OCEAN model"
          delay={0.1}
        >
          <div className="h-80">
            <ResponsiveContainer width="100%" height="100%">
              <RadarChart data={bigFiveData} cx="50%" cy="50%" outerRadius="70%">
                <PolarGrid 
                  stroke="hsl(var(--border))" 
                  strokeOpacity={0.5}
                />
                <PolarAngleAxis 
                  dataKey="trait" 
                  tick={{ fill: 'hsl(var(--muted-foreground))', fontSize: 12 }}
                />
                <Radar
                  name="You"
                  dataKey="value"
                  stroke="hsl(187, 100%, 50%)"
                  fill="hsl(187, 100%, 50%)"
                  fillOpacity={0.3}
                  strokeWidth={2}
                />
              </RadarChart>
            </ResponsiveContainer>
          </div>
          <div className="mt-4 p-3 rounded-xl bg-muted/30 flex items-center gap-2">
            <Sparkles className="w-4 h-4 text-primary" />
            <span className="text-xs text-muted-foreground">Generated by analyzing your data across all connected platforms</span>
          </div>
        </ChartCard>

        {/* Personality Summary */}
        <GlassPanel variant="glow" className="flex flex-col" style={{ animationDelay: '0.2s' }}>
          <div className="flex items-center gap-3 mb-6">
            <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-primary/30 to-secondary/30 flex items-center justify-center">
              <Brain className="w-6 h-6 text-primary" />
            </div>
            <div>
              <h3 className="font-display font-semibold text-lg">Personality Summary</h3>
              <p className="text-sm text-muted-foreground">AI-generated insight</p>
            </div>
          </div>
          
          <p className="text-muted-foreground leading-relaxed mb-6">
            {personalityData.summary}
          </p>

          <div className="space-y-4 mt-auto">
            <h4 className="font-semibold text-sm">Key Personality Markers</h4>
            {Object.entries(personalityData.bigFive).map(([key, value], index) => (
              <motion.div
                key={key}
                initial={{ opacity: 0, x: -20 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ delay: 0.3 + index * 0.1 }}
                className="space-y-1"
              >
                <div className="flex justify-between text-sm">
                  <span className="capitalize text-muted-foreground">{key}</span>
                  <span className="font-medium text-primary">{value}%</span>
                </div>
                <div className="h-2 rounded-full bg-muted overflow-hidden">
                  <motion.div
                    initial={{ width: 0 }}
                    animate={{ width: `${value}%` }}
                    transition={{ delay: 0.5 + index * 0.1, duration: 0.8 }}
                    className="h-full rounded-full bg-gradient-to-r from-primary to-secondary"
                  />
                </div>
              </motion.div>
            ))}
          </div>
        </GlassPanel>
      </div>

      {/* Trait Cards */}
      <div>
        <motion.h2
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.4 }}
          className="font-display text-xl font-semibold mb-4"
        >
          Dominant Traits
        </motion.h2>
        <div className="grid md:grid-cols-3 lg:grid-cols-5 gap-4">
          {personalityData.traits.map((trait, index) => (
            <motion.div
              key={trait.name}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.5 + index * 0.1 }}
              className={cn(
                'p-5 rounded-2xl border bg-gradient-to-br backdrop-blur-xl text-center',
                colorClasses[trait.color as keyof typeof colorClasses]
              )}
            >
              <p className="text-3xl font-display font-bold mb-1">{trait.score}%</p>
              <p className="font-medium">{trait.name}</p>
            </motion.div>
          ))}
        </div>
      </div>
    </div>
  );
};

export default Personality;
